name: Devops Workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout de Codigo
        uses: actions/checkout@v6
      - name: Mostrar Mensagem
        run: echo "Ola, Mundo Devops!"
        